repositories:
  prod:
    url: git://github.com/byronsalty/simple-notify.git
    checkout-to: /tmp/sn
    type: git
    commands: examples/prod/
    alert: byron@saltylabs.com
    subject: Prod failures
  dev:
    url: git://github.com/byronsalty/simple-notify.git
    checkout-to: /tmp/sn
    type: git
    commands: examples/dev/
    alert: byron@saltylabs.com
    subject: Dev failures
